CREATE DATABASE BD_SIRIUS;
USE BD_SIRIUS;


CREATE TABLE USUARIO(
    ID_USU INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_USU VARCHAR(50) NOT NULL,
    EMAIL_USU VARCHAR(60) NOT NULL,
    SENHA_USU VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(20) NOT NULL,
    DESCRICAO_USU VARCHAR(200),
    FOTO_USU VARCHAR(255)
) ENGINE=INNODB;


CREATE TABLE DISCIPLINA(
    ID_DISCI INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_DISCI VARCHAR(30) NOT NULL
) ENGINE=INNODB;


CREATE TABLE NIVEL_ENSINO(
    ID_NIVEL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_NIVEL VARCHAR(30) NOT NULL
) ENGINE=INNODB;


CREATE TABLE CONTEUDO(
    ID_CONTEUDO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COD_DISCI INT NOT NULL,
    NOME_CONTEUDO VARCHAR(30),

    FOREIGN KEY (COD_DISCI) REFERENCES DISCIPLINA(ID_DISCI)
) ENGINE=INNODB;


CREATE TABLE MATERIAL(
    ID_MATERIAL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COD_USU INT NOT NULL,
    COD_CONTEUDO INT NOT NULL,
    COD_NIVEL INT NOT NULL,
    TITULO_MATERIA VARCHAR(50) NOT NULL,
    CAMINHO_ARQUIVO VARCHAR(255) NOT NULL,
    NOME_ARQUIVO VARCHAR(255) NOT NULL,
    DATA_CAD DATE NOT NULL,
    STATUS_MATERIA VARCHAR(10) NOT NULL,
    FOREIGN KEY (COD_USU) REFERENCES USUARIO(ID_USU),
    FOREIGN KEY (COD_CONTEUDO) REFERENCES CONTEUDO(ID_CONTEUDO),
    FOREIGN KEY (COD_NIVEL) REFERENCES NIVEL_ENSINO(ID_NIVEL)
) ENGINE=INNODB;


CREATE TABLE PLANEJAMENTO(
    ID_PLANEJAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TITULO_PLAN VARCHAR(30) NOT NULL,
    ASSUNTO VARCHAR(100) NOT NULL,
    DATA_AULA DATE NOT NULL,
    SALA VARCHAR(30) NOT NULL
) ENGINE=INNODB;


INSERT INTO NIVEL_ENSINO (NOME_NIVEL) 
VALUES('Ens. Fundamental I'),
('Ens. Fundamental II'),
('Ens. Médio'),
('Ens. Superior');