CREATE DATABASE BD_SIRIUS;
USE BD_SIRIUS;


CREATE TABLE USUARIO(
    ID_USU INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_USU VARCHAR(50) NOT NULL,
    EMAIL_USU VARCHAR(60) NOT NULL,
    SENHA_USU VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(20) NOT NULL,
    DESCRICAO_USU VARCHAR(200),
    FOTO_USU VARCHAR(255)
) ENGINE=INNODB;


CREATE TABLE DISCIPLINA(
    ID_DISCI INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_DISCI VARCHAR(30) NOT NULL
) ENGINE=INNODB;


CREATE TABLE NIVEL_ENSINO(
    ID_NIVEL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_NIVEL VARCHAR(30) NOT NULL
) ENGINE=INNODB;


CREATE TABLE CONTEUDO(
    ID_CONTEUDO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COD_DISCI INT NOT NULL,
    NOME_CONTEUDO VARCHAR(30),

    FOREIGN KEY (COD_DISCI) REFERENCES DISCIPLINA(ID_DISCI)
) ENGINE=INNODB;


CREATE TABLE MATERIAL(
    ID_MATERIAL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COD_USU INT NOT NULL,
    COD_CONTEUDO INT NOT NULL,
    COD_NIVEL INT NOT NULL,
    TITULO_MATERIA VARCHAR(100) NOT NULL,
    CAMINHO_ARQUIVO VARCHAR(255) NOT NULL,
    NOME_ARQUIVO VARCHAR(255) NOT NULL,
    DATA_CAD DATE NOT NULL,
    STATUS_MATERIA VARCHAR(10) NOT NULL,
    DESCRICAO_MATERIA VARCHAR(300),
    FOREIGN KEY (COD_USU) REFERENCES USUARIO(ID_USU),
    FOREIGN KEY (COD_CONTEUDO) REFERENCES CONTEUDO(ID_CONTEUDO),
    FOREIGN KEY (COD_NIVEL) REFERENCES NIVEL_ENSINO(ID_NIVEL)
) ENGINE=INNODB;


CREATE TABLE PLANEJAMENTO(
    ID_PLANEJAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COD_USU INT NOT NULL,
    TITULO_PLAN VARCHAR(50) NOT NULL,
    ASSUNTO VARCHAR(100) NOT NULL,
    DATA_AULA DATE NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIM TIME NOT NULL,
    SALA VARCHAR(50) NOT NULL,
    STATUS_PLAN VARCHAR(10) NOT NULL,
    FOREIGN KEY (COD_USU) REFERENCES USUARIO(ID_USU)
) ENGINE=INNODB;

CREATE TABLE LIGACAO(
    ID_LIGACAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COD_USU INT NOT NULL,
    COD_USU_DESTINO INT NOT NULL,
    STATUS_LIGACAO VARCHAR(10) NOT NULL,
    DATA_LIGACAO DATE NOT NULL,
    FOREIGN KEY (COD_USU) REFERENCES USUARIO(ID_USU),
    FOREIGN KEY (COD_USU_DESTINO) REFERENCES USUARIO(ID_USU)
) ENGINE=INNODB;

CREATE TABLE PLANEJAMENTO_MATERIAL(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COD_PLANEJAMENTO INT NOT NULL,
    COD_MATERIAL INT NOT NULL,
    FOREIGN KEY (COD_PLANEJAMENTO) REFERENCES PLANEJAMENTO(ID_PLANEJAMENTO),
    FOREIGN KEY (COD_MATERIAL) REFERENCES MATERIAL(ID_MATERIAL)
) ENGINE=INNODB;


INSERT INTO NIVEL_ENSINO (NOME_NIVEL) 
VALUES('Ens. Fundamental I'),
('Ens. Fundamental II'),
('Ens. Médio'),
('Ens. Superior');

CREATE TABLE PASTA (
    ID_PASTA INT AUTO_INCREMENT PRIMARY KEY,
    COD_USU INT NOT NULL,
    NOME_PASTA VARCHAR(50) NOT NULL,

    FOREIGN KEY (COD_USU) REFERENCES USUARIO(ID_USU)
);

CREATE TABLE MATERIAL_SALVO (
    ID_SALVO INT AUTO_INCREMENT PRIMARY KEY,
    COD_USU INT NOT NULL,
    COD_MATERIAL INT NOT NULL,
    COD_PASTA INT NOT NULL,
    DATA_SALVO DATE NOT NULL,

    FOREIGN KEY (COD_USU) REFERENCES USUARIO(ID_USU),
    FOREIGN KEY (COD_MATERIAL) REFERENCES MATERIAL(ID_MATERIAL),
    FOREIGN KEY (COD_PASTA) REFERENCES PASTA(ID_PASTA)
);

